### ISSUE TITLE
Qt6 : Piemenu is broken

### ISSUE THREAD

**Issue by Grubuntu** [Grubuntu/PieMenu#101]
Testing Piemenu under FreeCAD compiled with Qt6 shows that several functions are broken.

 - WA_MacAlwaysShowToolWindow flag is now considered as widget attribute instead of a window type...
```
self.menu.setWindowFlags(QtCore.Qt.FramelessWindowHint | Qt.NoDropShadowWindowHint | QtCore.Qt.WA_MacAlwaysShowToolWindow)
During initialization the error "unsupported operand type(s) for |: 'WindowType' and 'WidgetAttribute'

```

 - pressing the global shortcut no longer opens PieMenu :

```
18:00:56  Traceback (most recent call last):
18:00:56    File "C:\Users\Victus\AppData\Roaming\FreeCAD\Mod\PieMenu\.\InitGui.py", line 1565, in showAtMouse
18:00:56      self.showAtMouseInstance(keyValue, notKeyTriggered)
18:00:56    File "C:\Users\Victus\AppData\Roaming\FreeCAD\Mod\PieMenu\.\InitGui.py", line 1456, in showAtMouseInstance
18:00:56      updateCommands(keyValue)
18:00:56    File "C:\Users\Victus\AppData\Roaming\FreeCAD\Mod\PieMenu\.\InitGui.py", line 2408, in updateCommands
18:00:56      PieMenuInstance.add_commands(actions, context, text)
18:00:56                                   ^^^^^^^
18:00:56  UnboundLocalError: cannot access local variable 'actions' where it is not associated with a value
```

- it is impossible to assign a shortcut, the shortcut entry box no longer works
- 
```
18:04:15    File "C:\Users\Victus\AppData\Roaming\FreeCAD\Mod\PieMenu\.\InitGui.py", line 195, in keyPressEvent
18:04:15      modifier_text = self.get_modifier_text(event.modifiers())
18:04:15                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
18:04:15    File "C:\Users\Victus\AppData\Roaming\FreeCAD\Mod\PieMenu\.\InitGui.py", line 246, in get_modifier_text
18:04:15      for modifier in modifier_names if modifiers & modifier])
18:04:15                                        ~~~~~~~~~~^~~~~~~~~~
18:04:15  TypeError: unsupported operand type(s) for &: 'KeyboardModifier' and 'Key'
```

- workbenches toolbars feature is broken 
```

18:06:21  Traceback (most recent call last):
18:06:21    File "C:\Users\Victus\AppData\Roaming\FreeCAD\Mod\PieMenu\.\InitGui.py", line 3947, in onButtonToolBar
18:06:21      listToolBar = onListToolBar()
18:06:21                    ^^^^^^^^^^^^^^^
18:06:21    File "C:\Users\Victus\AppData\Roaming\FreeCAD\Mod\PieMenu\.\InitGui.py", line 1987, in onListToolBar
18:06:21      getGuiToolButtonData(command.text(), None, commands, None)
18:06:21    File "C:\Users\Victus\AppData\Roaming\FreeCAD\Mod\PieMenu\.\InitGui.py", line 2255, in getGuiToolButtonData
18:06:21      for widgets in action.associatedWidgets():
18:06:21                     ^^^^^^^^^^^^^^^^^^^^^^^^
18:06:21  AttributeError: 'PySide6.QtGui.QAction' object has no attribute 'associatedWidgets'. Did you mean: 'associatedObjects'?
```

- adding a tool to a piemenu breaks up the piemenu by inserting a huge number of tools

- context doesn't work properly

**Comment by Grubuntu** [comment]
Fix most of the bugs :
https://github.com/Grubuntu/PieMenu/pull/103
